# Generated by Django 6.0.5 on 2026-09-09 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_lattes', models.URLField(blank=True, null=True, verbose_name='Link do Lattes')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='projeto.aluno', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Projeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='projeto.categoria', verbose_name='Categoria')),
                ('equipe', models.ManyToManyField(related_name='projetos', to='projeto.aluno', verbose_name='Equipe do Projeto')),
            ],
        ),
    ]
